creacion de modelos
feavilan04/weather-app pull request #25
Opened 2022-06-29 19:15 UTC by LeidyNa

se hizo la creacion de algunos modelos

2022-06-30 20:17 UTC, feavilan04 requested changes
Super!, te deje unos comentarios de unas lineas, de resto todo esta super bien.

Apenas tengas los cambios pideme que los revise por aca en la seccion de reviewers.

Gracias!

2022-06-30 20:17 UTC, feavilan04 commented on weather_app/weather/models.py
> +from mailbox import NoSuchMailboxError
```suggestion
```
Esta linea fue una importación automatica que debio haber hecho VS code, la puedes borrar sin lio

2022-06-30 20:17 UTC, feavilan04 commented on weather_app/weather/models.py
> +from re import M
```suggestion
```
Esta igual

2022-06-30 20:17 UTC, feavilan04 commented on weather_app/weather/models.py
> +from statistics import mode
```suggestion
```
Esta también

2022-06-30 20:17 UTC, feavilan04 commented on weather_app/weather/models.py
> +    cantante = models.CharField(Cantante, on_delete=models.CASCADE)
```suggestion
    cantante = models.ForeignKey(Cantante, on_delete=models.CASCADE)
```

Recuerda que las foreign key van con el tipo de campo `models.ForeignKey`

2022-06-30 20:17 UTC, feavilan04 commented on weather_app/weather/models.py
> +    estudiante =models.CharField(Estudiante, on_delete=models.PROTECT)
```suggestion
    estudiante =models.ForeignKey(Estudiante, on_delete=models.PROTECT)
```
Aqui también cambia porfa el tipo de campo

2022-06-30 20:17 UTC, feavilan04 commented on weather_app/weather/models.py
> +    jugadorm = models.CharField(InscripcionJuegosMesa, on_delete=models.CASCADE)
```suggestion
    jugadorm = models.ForeignKey(InscripcionJuegosMesa, on_delete=models.CASCADE)
```

Aca también

2022-06-30 20:17 UTC, feavilan04 commented on weather_app/weather/models.py
> +    objeto = models.CharField(ObjetosEncontrados, on_delete=models.PROTECT)
```suggestion
    objeto = models.ForeignKey(ObjetosEncontrados, on_delete=models.PROTECT)
```
Este igual

2022-06-30 20:17 UTC, feavilan04 commented on weather_app/weather/models.py
> +    celular =models.CharField(Celulares, on_delete=models.CASCADE)
```suggestion
    celular =models.ForeignKey(Celulares, on_delete=models.CASCADE)
```
Aquí también

2022-06-30 20:17 UTC, feavilan04 commented on weather_app/weather/models.py
> +    usuario = models.CharField(RegistroUsuario, on_delete=models.PROTECT)
```suggestion
    usuario = models.ForeignKey(RegistroUsuario, on_delete=models.PROTECT)
```
aca también

2022-06-30 20:57 UTC, LeidyNa commented on weather_app/weather/models.py
> +from mailbox import NoSuchMailboxError
ya quedo

2022-06-30 20:59 UTC, LeidyNa commented on weather_app/weather/models.py
> +    celular =models.CharField(Celulares, on_delete=models.CASCADE)
listo

2022-06-30 21:00 UTC, LeidyNa commented on weather_app/weather/models.py
> +    cantante = models.CharField(Cantante, on_delete=models.CASCADE)
ya quedo arreglado

2022-06-30 21:01 UTC, LeidyNa commented on weather_app/weather/models.py
> +    estudiante =models.CharField(Estudiante, on_delete=models.PROTECT)
ya quedo

2022-06-30 21:01 UTC, LeidyNa commented on weather_app/weather/models.py
> +from statistics import mode
ya quedo

2022-06-30 21:07 UTC, feavilan04 requested changes
Un cambio en unos nombres

2022-06-30 21:07 UTC, feavilan04 commented on weather_app/weather/models.py
> +class FechaCumpleaños(models.Model):
```suggestion
class FechaCumpleannos(models.Model):
```
Python es un poquito delicado con el tema de caracteres especiales, como en inglés no existe la ñ es mejor que lo dejes con nn o n

2022-06-30 21:12 UTC, LeidyNa commented on weather_app/weather/models.py
> +class FechaCumpleaños(models.Model):
listo ya lo cambie

2022-07-05 18:34 UTC, feavilan04 approved these changes

2022-07-05 18:35 UTC, merged