desarrollo de vistas post
feavilan04/weather-app pull request #27
Opened 2022-07-07 20:44 UTC by LeidyNa

2022-07-12 14:58 UTC, LeidyNa commented on weather_app/weather/views.py
> +from statistics import correlation
listo

2022-07-14 23:17 UTC, feavilan04 requested changes
Todo lo veo super, solo unos comentarios de  los nombres de los campos, pero aparte de eso, todo esta ok

2022-07-14 23:17 UTC, feavilan04 commented on weather_app/weather/templates/weather/vistapost.html
> +  <input type="number" id="numeroIdentidad" name="numeroIdentidad"><br><br>
```suggestion
  <input type="number" id="numero_identidad" name="numero_identidad"><br><br>
```

Usualmente para los nombres y IDs se utilizan los valores delimitados por (_) todo te funciona ok pero para que lo miremos en los proximos IDs y names

2022-07-14 23:17 UTC, feavilan04 commented on weather_app/weather/views.py
> +        numeroidentidad = request.POST.get('numeroIdentidad')
```suggestion
        numeroidentidad = request.POST.get('numero_identidad')
```
Si cambias el nombre arriba, tambien te tocaria cambiarlo aqui porque la llave la va a tomar del name del campo

2022-07-18 22:36 UTC, feavilan04 approved these changes
Todo súper bien voy a unir el cambio a main

2022-07-18 22:36 UTC, merged